### ISSUE TITLE
eyre@0.6.12 missing in the repository?

### ISSUE THREAD

**Issue by Turbo87** [eyre-rs/eyre#153]
The Rust blog got an update PR (https://github.com/rust-lang/blog.rust-lang.org/pull/1237) for eyre@0.6.12, but I can't seem to find any information on it in this repository. Was this a legitimate release? The latest release in the corresponding changelog file is for 0.6.11 apparently.

**Comment by ten3roberts** [comment]
https://github.com/eyre-rs/eyre/tree/release-0.6

It is on the stable branch, as we are pushing to a breaking change towards a 1.0.0 on master.

Releases are backported to release branches.

I agree that it would make much more sense to also have a single account publish the release, rather than changing by whoever is most available.

**Comment by Turbo87** [comment]
I see. Must have missed that branch when I looked. Sorry for the noise :)
